server:
  servlet:
    context-path: /
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: asl-data-parser
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@103.231.135.60:1521:orcl
    username: DESCO
    password: Desco1234
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jackson:
    serialization:
      indent-output: true
  banner:
    location: banner.txt


dp: 
  properties-path: D:/ASL/asl.properties
  module: 
    active: MONTHLY
    monthly: 
      thread: 
        number: 2
        sleep: 1
      file: 
        prefix: "02_"
        readpath: D:/ASL
        successpath: D:/ASL/monthly/success
        errorpath: D:/ASL/monthly/error
        archivepath: D:/ASL/monthly/archive
    daily:
      thread: 
        number: 1
        sleep: 5
      file: 
        prefix: "01_"
        readpath: D:/ASL
        successpath: D:/ASL/daily/success
        errorpath: D:/ASL/daily/error
        archivepath: D:/ASL/daily/archive







